# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    #- name: Push code to Heroku Git repo
    #  run: git push heroku dev:master

    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: "steevinbradlee-site-dev"
      run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/dev:master

    #- name: Login to Heroku Container registry
    #  env: 
    #    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    #  run: heroku container:login 

    #- name: Build and push
    #  env:
    #    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    #  run: heroku container:push -a steevinbradlee-site-dev 

    #- name: Release
    #  env:
    #    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    #  run: heroku container:release -a steevinbradlee-site-dev 
